# TODO: Update baseURL once deployed to InSiliChem.com
baseURL = "https://jovial-noyce-98deec.netlify.com"
languageCode = "en-us"
title = "InSiliChem - Chemobiological molecular modeling"
theme = "timer-hugo"

# Navbar Menus
[[menu.nav]]
name    = "Research Lines"
url     = "research"
weight  = 2
[[menu.nav]]
name    = "Publications"
url     = "publications"
weight  = 3
[[menu.nav]]
name    = "Software and Services"
url     = "services"
weight  = 4
[[menu.nav]]
name    = "News"
url     = "news"
weight  = 5
[[menu.nav]]
name    = "About us"
url     = "about"
weight  = 6
[[menu.nav]]
name    = "Contact"
url     = "contact"
weight  = 7

# Site Params
[params]
home = "Home"
logo = "/images/logo_green.png"
dateFormat = "6 January 2006"
# Meta data
description = "Led by Dr. Maréchal, our group focuses on the modeling of systems at the interface between chemistry and biology."
author = "InSiliChem"
# Google Analitycs
googleAnalitycsID = "Your ID"

# Banner Section
[params.banner]
enable  = true
bgImage = "/images/slider.jpg"
heading = "InSiliChem"
description = "for the study and design of chemobiological systems"
# button
btn     = true
btnText = "Know more"
btnURL  = "/about"
# flip text
[[params.banner.flipText]]
title   = "Molecular Modeling"
[[params.banner.flipText]]
title   = "Computational Chemistry"
[[params.banner.flipText]]
title   = "Medicinal Chemistry"
[[params.banner.flipText]]
title   = "Enzyme Design"
[[params.banner.flipText]]
title   = "Software Development"

# Homepage About Section
[params.about]
enable  = true
title   = "Briefly..."
content = "Led by Prof. Jean-Didier Maréchal <a href='/cv_jdmarechal_web_2020.pdf' target='_blank' >(cv)</a>, InSiliChem is a team that focuses on the modeling of systems at the interface between <strong>chemistry and biology</strong>. En el Briefly…, pots fer el copiar y pegar de això please. We have broad research interests although our primarily fields of research are the development of new chemobiological hybrids (e.g. artificial enzymes, metallopeptides, biomarkers,…) as well as the identification of bioactive compounds and the study of their pharmacological profiles (e.g. screening of natural compounds against therapeutic drugs, transition metal based therapies, prediction of P450 metabolism,…). One of the particularity of the group is to focus on metal mediated processes.<br /> Our work is sustained by a large number of methods from protein-ligand docking to QM/MM but we also intensively work on structural bioinformatics and computational chemistry methodological developments like a multi-scale platform, new analysing tools and a modular molecular sketcher called GaudiMM. Most of these efforts are performed using Python as a principal scripting language. <br /> We have a large network of collaborations worldwide both with experimental and theoretical groups leader in these fields.<br /> "
image   = "/images/home.jpg"

# Portfolio Section On Homepage
[params.portfolio]
enable  = true
title   = "Latest Works"
subtitle= "Check our <a href='https://scholar.google.com/citations?user=1hjLUfgAAAAJ' target='_blank' >latest publications</a>."

# Call to Action
[params.cta]
enable  = true
title   = "Get in touch"
btnText = "Contact us"
btnURL  = "/contact"

# social icon
# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/
[[params.socialIcon]]
icon = "ion-social-github"
url = "https://github.com/insilichem"

[[params.socialIcon]]
icon = "ion-social-twitter"
url = "https://twitter.com/insilichem"

